### ISSUE TITLE
Role Change with Cloud Functions

### ISSUE THREAD

**Issue by HarishTeens** [dscnitrourkela/project-dates#17]
Once the NITR Verification happens on client-side, a cloud function is responsible for updating the field in the User DB.

**Comment by DesignrKnight** [comment]
Input
- UserID
- Updated Access Level

Work to be done in the function
- update access level in firebase
- update access level in Mongo

How it gets triggered
gets called by client or server. Would be decided soon

**Comment by PraisySam** [comment]
Hey I will do😊

**Comment by DesignrKnight** [comment]
Closing this as we were mistaken. Doing this using Cloud Functions is cumbersome
