### ISSUE TITLE
Upgrade Node.js Version

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-dates#56]
Latest Node.js version is 14 for LTS. 
Do check if our code works as expected for v14. If so, request all developers to use v14. 
Switching to LTS sooner will be easier than down the line when some things may break
https://nodejs.org/en/about/releases/

Feel free to close this with a comment if all works good

**Comment by HarishTeens** [comment]
@roshankshaw close the pull request if you have upgraded to Node 14, I am already at Node 14.
